# Generated by Django 3.0.6 on 2020-05-28 14:16

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.FileField(null=True, upload_to=projects.models.user_directory_path)),
                ('image_2', models.FileField(null=True, upload_to=projects.models.user_directory_path)),
                ('image_3', models.FileField(null=True, upload_to=projects.models.user_directory_path)),
                ('image_4', models.FileField(null=True, upload_to=projects.models.user_directory_path)),
                ('image_5', models.FileField(null=True, upload_to=projects.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Images')),
            ],
        ),
    ]
