# Generated by Django 3.0.6 on 2020-05-28 14:55

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AddField(
            model_name='project',
            name='image_1',
            field=models.FileField(null=True, upload_to=projects.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.FileField(null=True, upload_to=projects.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.FileField(null=True, upload_to=projects.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='project',
            name='image_4',
            field=models.FileField(null=True, upload_to=projects.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='project',
            name='image_5',
            field=models.FileField(null=True, upload_to=projects.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
